CREATE DATABASE orehovo_zuevo CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS streets (
   id SERIAL PRIMARY KEY,
   name VARCHAR (255) NOT NULL,
   cdate DATETIME NOT NULL
)ENGINE=MyISAM,CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS buildings (
   id SERIAL PRIMARY KEY,
   id_street BIGINT NOT NULL,
   name VARCHAR (255) NOT NULL,
   cdate DATETIME NOT NULL
)ENGINE=MyISAM,CHARACTER SET utf8 COLLATE utf8_general_ci;

